### PR TITLE
modify html

### PR DESCRIPTION
**Pull request by posh101**
## Setup For My Portfolio Project

- Create a new branch
- Add Html
- Add CSS
- Add linters
- create a portfolio with HTML and CSS

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @posh101, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights


## Required Changes ♻️
_Check the comments under the review._
## Kindly know that I would have made the comments on the code expected but there is actually no code to comment on so I am going to write as follows:
- [ ] The work section includes the individual cards under my recent work
- [ ] Kindly ensure that the 'My Recent Work' properly aligns with the line under it as it is on the figma.
- [ ] Kindly make your work section and the about section fit in for mobile screen properly

### Figma design
image

### Your Design
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @posh101 , 



Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️



## Required Changes ♻️
_Check the comments below._

- [ ] Please, kindly update the twitter image to `Twitter.png` as this the way you've spelled it in your images directory and that's why the Twitter image is broken.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- Update your readme as it is not very professional now. kindly use the microverse readme [template[(https://github.com/microverseinc/readme-template) to customize your readme by adding the remaining section relevant to the project to make your readme more professional.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ichala — CHANGES_REQUESTED** [review]
Hi @posh101 
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- Good Design✔️ 


 ## Required Changes ♻️

- [ ] 🛑🛑as mentioned by the previous reviewer:  **_kindly update the Twitter image to Twitter.png as this is the way you've named it in your images directory and that's why the Twitter image is broken._** 🛑🛑

## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by posh101** [comment]
The Twitter logo is showing on my end.

**Comment by posh101** [comment]
I have done what you said and the Twitter logo is showing on my end

**Comment by ichala** [comment]
@posh101 it's not showing for me neither locally or online, kindly just call it with the same exact name and it will show up

**Review by mckent05 — APPROVED** [review]
Hi @posh101, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 

## Highlights
- All linter checks are working correctly ✔️ ✔️ 

## Optional suggestions
**OPTIONAL** - Please, the Twitter icon is still not showing as noted by previous reviewers, I am only approving this because I see you do not have any more reviews left and I wouldn't want you repeating the week because of this issue. Can you kindly follow the advice of the previous reviewers, it won't take anything away from your code, please.

Your project:
yaga


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
